name: Workflow
on:
  push:
    branches:
      - feat-labdevsecops
      
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: validando la existencia proyecto sonarcloud
        id: validateProjectSonar
        run: |
          #pwd
          #ls -R
          set +e
          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}-curseg' -d 'organization=liliansaa' -d 'project=${{ github.event.repository.name }}-cursoseg' -d 'visibility=public'
          if [ $? -ne 0 ]; then 
            echo "Proyecto ya existe en SonarCloud"
            echo "::set-output name=proyectoExiste::1"
          else
            echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
            
            echo "Se establece rama feat como rama por defecto"
            curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=feat-labdevsecops' -d 'project=${{ github.event.repository.name }}-curseg' 
          fi
          set -e

      - name: Configure Node Project
        uses: actions/setup-node@v4

      - name: Install SonarCloud Node JS
        run : npm install -g @sonar/scan

      - name: Configure NodeJs Project
        run : npm install 

      - name: Run SonarCube on Project
        run : sonar-scanner -Dsonar.token=${{secrets.SONAR_TOKEN}} -Dsonar.organization=liliansaa  -Dsonar.projectKey=${{github.event.repository.name}}-curseg
      
      - name : Obtaing results from SonarCloud
        run :  |
          issueValidate=$(curl -s -X GET -u '${{secrets.SONAR_TOKEN}}:' 'https://sonarcloud.io/api/issues/search?branch=feat-labdevsecops&componentKeys=${{github.event.repository.name}}-curseg&types=VULNERABILITY&severities=MAJOR,CRITICAL,BLOCKER' | jq '.total')
          echo "Cantidad de Issues MAJOR,CRITICAL,BLOCKER : $issueValidate"
          if [ "$issueValidate" -gt 0 ]; then
            echo "Se encontraron issues bloqueantes. Se quiebra el pipeline."
            exit 1
          else
            echo "No se encontraron issues bloqueantes. Pipeline Continua."
          fi       
