name: Workflow
on:
  push:
    branches:
      - feat-labdevsecops
      
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: validando la existencia proyecto sonarcloud
        id: validateProjectSonar
        run: |
          #pwd
          #ls -R
          set +e
          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}-curseg' -d 'organization=liliansaa' -d 'project=${{ github.event.repository.name }}-curseg' -d 'visibility=public'
          if [ $? -ne 0 ]; then 
            echo "Proyecto ya existe en SonarCloud"
            echo "::set-output name=proyectoExiste::1"
          else
            echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
            
            echo "Se establece rama feat como rama por defecto"
            curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=feat-labdevsecops' -d 'project=${{ github.event.repository.name }}-curseg' 
          fi
          set -e
      - name: Ejecutando SonarCloud
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #run: |
         # ./gradlew sonarqube -Dsonar.projectKey=${{ github.event.repository.name }}-cursoseg -Dsonar.organization=testing-devsecops -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.branch.name=main 
   # -name: Validando resultado de Sonarcloud
   #  run: |
   #   issueValidate=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/issues/search?branch=feat-labdevsecops&componentsKeys=${{ github.event.repository.name }}-cursoseg'&facets=severities)
